// This file is generated by Slice Machine. Update with care!

import Featured Work from './Featured Work';
import Featured Work from './Featured Work';

export {
	Featured Work,
	Featured Work,
};

export const components = {
	featured_work: Featured Work,
	featured_work: Featured Work,
};
