// This file is generated by Slice Machine. Update with care!

import Featured from './Featured';
import Section from './Section';

export {
	Featured,
	Section,
};

export const components = {
	featured: Featured,
	section: Section,
};
